test: &test
  database: pg_party_<%= Rails.env %>
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: postgres
  schema_search_path: e9651f34
  port: 5432
  pool: 50

development:
  <<: *test
